version: "3.9"

services:
  db:
    platform: linux/x86_64
    image: mysql
    container_name: mysqlAccount
    ports:
      - "3308:3306"
    volumes:
      - ./:/app/
    environment:
      MYSQL_DATABASE: account
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: user
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - account-net

  app:
    container_name: accountService
    command: java -jar target/account-0.0.1-SNAPSHOT.jar
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    depends_on:
      db:
        condition: service_healthy

    volumes:
      - ./:/app/app

    networks:
      - account-net
    environment:
      spring.datasource.url: jdbc:mysql://mysqlAccount:3306/account?useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      spring.datasource.username: user
      spring.datasource.password: user


networks:

  account-net:
    name: account-net
